name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Create deployment directory
        run: mkdir -p ./deploy
        
      - name: Copy main landing page
        run: |
          if [ -f "./index.html" ]; then
            cp ./index.html ./deploy/
          fi
      
      - name: Create project directories
        run: |
          mkdir -p ./deploy/Visual-Metaphysics-No2-Reincarnation/site
          mkdir -p ./deploy/Visual-Metaphysics-No1-FlyingSaucers/site
      
      - name: Copy project site files
        run: |
          cp -r ./Visual-Metaphysics-No2-Reincarnation/site/* ./deploy/Visual-Metaphysics-No2-Reincarnation/site/
          cp -r ./Visual-Metaphysics-No1-FlyingSaucers/site/* ./deploy/Visual-Metaphysics-No1-FlyingSaucers/site/
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './deploy'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
